on:
  schedule:
    # Every day at 9:30 UTC/5:30 ET
    - cron:  '30 9 * 1,2,2-9 *'
  workflow_dispatch:
  
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::tidyr
            any::rvest
            any::stringr
            any::janitor
            any::nflreadr
            any::cli
            any::glue
            sportsdataverse/cfbfastR

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Scrape Players
        run: Rscript -e 'source("R/scrape_players.R")'

      - name: Scrape Depth Charts
        run: Rscript -e 'source("R/scrape_espn_depth_charts.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
